app:
    resource: '@AppBundle/Controller/'
    type: annotation

frontend:
    resource: '@FrontendBundle/Controller/'
    type: annotation

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"